spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ssense
    username: root
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  jwt:
    secret: asjdklasjlkdjasklfjgiosrjklvcasdiohguiahjkfhndjgh

logging:
  level:
    web: "info"